### ISSUE TITLE
profiles dir should not lie in this repo

### ISSUE THREAD

**Issue by apinsard** [funtoo/ego#11]
I think profiles directory should not be versioned. This is not intended to be modified here and this would require a recurring update.

We should rather have a Makefile such as:

```makefile
install:
    cp -r /usr/portage/profiles profiles
    # or
    ln -sf /usr/portage/profiles profiles
    # or 
    wget ...
```

and add `/profiles` to `.gitignore`

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2859

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
