### ISSUE TITLE
Why not use pep8 code style? Just like what the portage do?

### ISSUE THREAD

**Issue by m31271n** [funtoo/ego#4]

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2346

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
